# Generated by Django 2.2.5 on 2020-01-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='文章标题')),
                ('label', models.CharField(max_length=30, verbose_name='文章标签')),
                ('release', models.CharField(choices=[('n', 'no'), ('y', 'yes')], max_length=2, verbose_name='是否发布')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('save_time', models.DateTimeField(auto_now=True, verbose_name='保存日期')),
                ('hit_count', models.BigIntegerField(default=0, verbose_name='点击次数')),
            ],
        ),
    ]
