# Generated by Django 2.2.8 on 2020-03-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='release',
            field=models.CharField(choices=[('y', '已发布'), ('n', '未发布')], default='未发布', max_length=2, verbose_name='是否发布'),
        ),
        migrations.AlterField(
            model_name='label',
            name='release',
            field=models.CharField(choices=[('y', '已发布'), ('n', '未发布')], default='未发布', max_length=2, verbose_name='是否发布'),
        ),
    ]
