# Generated by Django 2.2.5 on 2020-01-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.CharField(default='wu', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='release',
            field=models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=2, verbose_name='是否发布'),
        ),
    ]
